eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 3
    appname: FIRMAEC-SERVICES
  client:
    serviceUrl:
      defaultZone: http://192.168.200.15:8710/eureka/