
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 3
    appname: FIRMAEC-SERVICES
  client:
    #    serviceUrl:
    #      defaultZone: http://192.168.100.10:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

