server:
  port: 8780

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    appname: ZULL-SERVICES
  client:
    serviceUrl:
      defaultZone: http://200.124.240.62:8761/eureka/

zuul:
  routes:
    ventanilla-ws:
      path: /ventanilla-ws/**
      serviceId: ventanilla-ws
      stripPrefix: true
      url: http://127.0.0.1:8721/
    media-ws:
      path: /media-ws/**
      serviceId: media-ws
      stripPrefix: true
      url: http://127.0.0.1:8722/
    dinardap:
      path: /dinardap/**
      serviceId: dinardap
      stripPrefix: true
      url: http://127.0.0.1:8785/
    facturacion:
      path: /facturacion/**
      serviceId: facturacion
      stripPrefix: true
      url: http://127.0.0.1:8786/

  sensitiveHeaders: Cookie,Set-Cookie

hystrix:
  command:
    atlantis-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
