spring:
  application:
    name: RPM-DINARDAP-SERVICES 

  datasource:
    url: jdbc:postgresql://192.168.16.215:5432/dinardap
    username: sisapp
    password: Postgr3s*BD
    platform: postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      pool-name: DinardapPoolWS
      max-lifetime: 1800


  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
  #main:
   # allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
      
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: /opt/servicios/logs/dinardap.log