server:
    port: 8790 

spring:
  profiles:
    active: prod
  application:
    name: RPL-DINARDAP-SERVICES
 

app:
  urlInterOperatividad: https://interoperabilidad.dinardap.gob.ec/interoperador-v2?wsdl
  interOperatividadUser: RpcLInter19
  interOperatividadPass: i1-AYEYSblGg-T
  paqueteDemografico: 2416
  paqueteSri: 2419
  parametroDemograficoSri: identificacion