spring:
  application:
    name: WS-ZERVICES
  datasource:
    url: jdbc:postgresql://127.0.0.1:5677/rpm_playas_ventanilla
    #url: jdbc:postgresql://127.0.0.1:5432/rpm_playas_ventanilla
    username: sisapp
    password: sisapp98
    platform: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      pool-name: WSRp
      max-lifetime: 30000
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: app
    hibernate:
      ddl-auto: update

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 3
    appname: ZULL-ZERVICES
  client:
    fetch-registry: false
    register-with-eureka: false

app:

  correo: origami.supergold@gmail.com
  claveCorreo: solutions
  hostCorreo: smtp.gmail.com
  portCorreo: 587
  entidad: REGISTRO MUNICIPAL CANTON PLAYAS

  outputDir: C:/servers_files/tramites/

  userSgr: ventanilla
  passSgr: regproloja

  dominio: http://localhost:9090/#
  #docUrl: jdbc:postgresql://192.168.100.12:5432/rpm_playas_archivos
  docUrl: jdbc:postgresql://127.0.0.1:5677/rpm_playas_archivos
  dbDocUser: sisapp
  dbDocPass: sisapp98

  logo: https://rpv.digital/rmppm.png
  urlPdfFirmado: http://127.0.0.1:8085/rpm-ventanilla/api/documento/
  urlDinardap: http://200.124.240.62:8790/api/dinardap/aplicacion/SIGERI/persona/identificacion/
  usuarioDinardap: rpventanilla
  claveDinardap: ventanilla@2021

  urlFichaRegistral: http://192.168.200.17:8790/api/rpl/fichaRegistral/ventanilla?numFicha=
  apiSms: http://200.124.240.36/api/sms.php?token=4PruebaOficina&no=

  rpFacturas: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/facturacionElectronica/
  rpConsultarTramite: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/consultar/tramite/
  rpIniciarTramite: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/iniciarTramiteOnline
  rpActualizarDocumentos: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/updatePubSolicitud
  rpActualizarRequisitos: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/actualizarRequisitos
  rpConsultarOidDocument: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/certificado/codigo/
  rpConsultarOidInscripcion: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/inscripcion/codigo/
  rpConsultarOid: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/documento/codigo/
  rpEntregaTramiteAPP: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/entregaTramiteAPP/tramite/
  rpActoInscripciones: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/inscripciones
  rpIniciarTramiteSolicitudInscripcion: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/iniciarTramiteSolicitudInscripcion
  rpIniciarTramiteInscripcion: http://127.0.0.1:8080/sigeri-playas/rest/ventanilla/iniciarTramiteInscripcion

  payphoneError: CONEXIÓN NO DISPONIBLE CON EL PROVEEDOR DE PAGOS
  payphoneTransactionCreate: https://pay.payphonetodoesposible.com/api/v2/transaction/Create
  payphoneReverseClient: https://pay.payphonetodoesposible.com/api/Reverse/Client

  payphoneBtnPago: https://pay.payphonetodoesposible.com/api/button/Prepare
  payphoneBtnApiCoding: 14fad1ec537e4c5689c483fa9096476e
  payphoneBtnBearerApiToken: TV6nh1ouGCF5ldkcQENrqbNp9MEbS3CqnXvQekxs5Sas9a12P4ev_vCTjxoAsiD6IgHMudPLyrOdxhFouxzYtcAtc3o4cvvP8cihvYd1xg4z9N0Vj7vAy1x4BHw7mk6ICkI-OYlAh1pIZRFP4wWBYS3wGcDHklnQrbk8Oq33n5sYjg93oFlCHLZPVcgMadRUEBPGlrxNgdlbMJxSURLWf1SLYgy0CDFhD43W4PAZRLW7DKUrvedijeMgLZgKqL3CPDu96szbGw2JfoK9x_3ESF_MlfCdKjk3v20wvENb_74AebYMyt5RqVThPjBX1IFBdKyi3Q

  payphoneConfirmPago: https://pay.payphonetodoesposible.com/api/button/V2/Confirm

  firmaElectronica: http://127.0.0.1:8781/api/firmaElectronica/


