
spring:
  application:
    name: WS-ZERVICES
  datasource:
    url: jdbc:postgresql://192.168.16.212:5432/rpm_playas_ventanilla
    username: sisapp
    password: sisapp98
    platform: postgres
    #driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      pool-name: WSRp
      max-lifetime: 30000
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: app

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 3
    appname: WSRP-ZERVICES
  client:
    fetch-registry: false
    register-with-eureka: false


app:
  correo: tramites.registro.playas@gmail.com
  claveCorreo: p14y45@c0rre0
  hostCorreo: smtp.gmail.com
  portCorreo: 587
  entidad: REGISTRO MUNICIPAL CANTON PLAYAS

  outputDir: /servers_files/tramites/

  userSgr: ventanilla
  passSgr: regproloja

  dominio: https://tramitesenlinea.rmpplayas.gob.ec/#
  docUrl: jdbc:postgresql://192.168.16.212:5432/rpm_playas_archivos
  dbDocUser: sisapp
  dbDocPass: sisapp98

  logo: https://tramitesenlinea.rmpplayas.gob.ec/rmppm.png
  urlPdfFirmado: https://rpv.digital/ws/rpm-ventanilla/api/documento/
  urlDinardap: http://127.0.0.1:8790/api/dinardap/aplicacion/SIGERI/identificacion/
  usuarioDinardap: rpventanilla
  claveDinardap: ventanilla@2021


  urlFichaRegistral: http://192.168.16.211/sigeri-playas/api/rpl/fichaRegistral/ventanilla?numFicha=
  apiSms: http://200.124.240.36/api/sms.php?token=8origamiec2021&no=

  rpFacturas: http://192.168.16.211/sigeri-playas/rest/ventanilla/facturacionElectronica/
  rpConsultarTramite: http://192.168.16.211/sigeri-playas/rest/ventanilla/consultar/tramite/
  rpIniciarTramite: http://192.168.16.211/sigeri-playas/rest/ventanilla/iniciarTramiteOnline
  rpActualizarDocumentos: http://192.168.16.211/sigeri-playas/rest/ventanilla/updatePubSolicitud
  rpActualizarRequisitos: http://192.168.16.211/sigeri-playas/rest/ventanilla/actualizarRequisitos
  rpConsultarOidDocument: http://192.168.16.211/sigeri-playas/rest/ventanilla/certificado/codigo/
  rpConsultarOidInscripcion: http://192.168.16.211/sigeri-playas/rest/ventanilla/inscripcion/codigo/
  rpConsultarOid: http://192.168.16.211/sigeri-playas/rest/ventanilla/documento/codigo/
  rpEntregaTramiteAPP: http://192.168.16.211/sigeri-playas/rest/ventanilla/entregaTramiteAPP/tramite/
  rpActoInscripciones: http://192.168.16.211/sigeri-playas/rest/ventanilla/inscripciones
  rpIniciarTramiteSolicitudInscripcion: http://192.168.16.211/sigeri-playas/rest/ventanilla/iniciarTramiteSolicitudInscripcion
  rpIniciarTramiteInscripcion: http://192.168.16.211/sigeri-playas/rest/ventanilla/iniciarTramiteInscripcion

  payphoneError: CONEXIÓN NO DISPONIBLE CON EL PROVEEDOR DE PAGOS
  payphoneTransactionCreate: https://pay.payphonetodoesposible.com/api/v2/transaction/Create
  payphoneReverseClient: https://pay.payphonetodoesposible.com/api/Reverse/Client

  payphoneBtnPago: https://pay.payphonetodoesposible.com/api/button/Prepare
  payphoneBtnApiCoding: 8cb80d8e924f4ee78ad559af65a43b0c
  payphoneBtnBearerApiToken: RxB5ae37Y-MI6F3NqhI_1tOSNtOCPuOOoWa9g-cvoXMKd4EZ826iU_frrYlOUU4EW5yAXIAHGMVH5upEUojIlnq6nFh64AqvIP9PD4UrkJCaujtFfbwM9w-s8KSf44tNyzN1e7jRCqrEr09if4E6g0QI7RlNQnH0dvgA1qYrx-kIKdKHOmKRIUi0VuC5NfPU_vXQq2bRio4BVyTU5EsKnP9U1ZFVhPxB0JlB7kW2KNg9RpvT-wn0t09vmr4VBqwtlHLBWsnHNAhgpIVXRsonnNVts20r9Ygm7d8uiZXeKMQurAWJ8vwBQtW6whSyIn49r2Y2TQ

  payphoneConfirmPago: https://pay.payphonetodoesposible.com/api/button/V2/Confirm

  firmaElectronica: http://192.168.16.213:8781/api/firmaElectronica/
