package ec.gob.ventanilla.resources;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/rpm-ventanilla/api/terminosCondicion")
public class TerminosCondicionResource {

    @RequestMapping(method = RequestMethod.GET)
    public ResponseEntity<String> terminosCondiciones() {
        
        String body = "  <h1>\n"
                + "                    Términos y Condiciones de Uso\n"
                + "                </h1>\n"
                + "                \n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    Los siguientes términos y condiciones rigen el uso que usted le dé al sitio web y a la aplicación móvil \n"
                + "                    del Registro de la Propiedad del Cantón Loja, \n"
                + "                    a cualquiera de los contenidos disponibles mediante este sitio web y aplicativo móvil. \n"
                + "                </h4>\n"
                + "                \n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    El Registro de la Propiedad del cantón Loja, puede cambiar los Términos y Condiciones en cualquier \n"
                + "                    momento sin ninguna notificación particular, únicamente publicando los cambios en el Sitio Web. \n"
                + "                </h4>\n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    AL USAR EL SITIO WEB Y/O NUESTRA APLICACIÓN MÓVIL, USTED ACEPTA Y ESTÁ DE ACUERDO CON ESTOS TÉRMINOS Y CONDICIONES. Si usted no está de acuerdo con estos Términos y Condiciones, \n"
                + "                    no puede tener acceso al mismo ni usar el Sitio Web y la Aplicación Móvil de ninguna otra manera.\n"
                + "                <br></br> En caso de presentar algun inconveniente reportar al siguiente correo: <b> tramites.registro.propiedad.loja@gmail.com "
                + "                </h4>\n"
                + "                \n"
                + "                <h3 style=\"padding-left: 10px\">\n"
                + "                    1.\tSERVICIOS EN LINEA:\n"
                + "                </h3>\n"
                + "                \n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    El servicio ofrecido mediante el Sitio Web y Aplicación Móvil \n"
                + "                    es exclusivamente para las solicitudes de <b>\"CERTIFICADOS REGISTRALES\".</b>\n"
                + "                </h4>\n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    1.1.\tCERTIFICADO HISTORIADO     \n"
                + "                </h4>\n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    El valor establecido del certificado historiado corresponde a la búsqueda de un periodo de 15 años, \n"
                + "                    si el solicitante requiere información \n"
                + "                    mayor a ese tiempo deberá cancelar el arancel establecido en la Ordenanza No. 047-2017 (24-05-2017).       \n"
                + "                </h4>\n"
                + "                <h3 style=\"padding-left: 10px\">\n"
                + "                    2.\tRESPONSABILIDAD\n"
                + "                </h3>\n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    En caso de usar un numero de indentificación de otra persona y esta reporte inconvenientes sera cancelada. <br></br>"
                + "                      \n La información proporcionada en las solicitudes realizadas por el usuario es de absoluta responsabilidad \n"
                + "                    de quien las ingresa. \n"
                + "                    Por lo que el Registro de la Propiedad del Cantón Loja no se responsabiliza por "
                + "la información brindada.   \n"
                + "                </h4>   \n"
                + "                <h3 style=\"padding-left: 10px\">\n"
                + "                    3.\tFORMAS DE PAGO\n"
                + "                </h3>\n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    El Sitio Web y la Aplicación Móvil permiten realizar dos formas de pago:                    \n"
                + "                </h4>\n"
                + "                <h4 style=\"padding-left: 50px\">\n"
                + "                    * Ventanilla Del Registro <p></p>\n"
                + "                    * Pago En Línea\n"
                + "                </h4>\n"
                + "                <h3 style=\"padding-left: 10px\">\n"
                + "                    VENTANILLA DEL REGISTRO:\n"
                + "                </h3>\n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    En esta forma de pago se genera un Número de Trámite que es enviado al correo electrónico del solicitante, con el que el usuario se debe acercar a las Ventanillas \n"
                + "                    de Recaudación del Registro de la Propiedad del Cantón Loja, a cancelar el valor correspondiente.\n"
                + "                </h4>\n"
                + "                <h3 style=\"padding-left: 10px\">\n"
                + "                    PAGO EN LINEA\n"
                + "                </h3>\n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    Las tarjetas permitidas son Crédito y Débito: MasterCard y VISA de cualquier entidad bancaria. El pago no podrá ser diferido.\n"
                + "                    A partir de Enero de 2020 cada transacción tendrá un valor adicional de $0.50 "
                + "centavos que representa el costo establecido por la Institución Financiera a la que pertenece la \n"
                + "                    Tarjeta con la que se realiza el pago. (Monto que no ingresa al Registro).\n"
                + "                    En caso de pérdida de la Tarjeta Bancaria el Registro de la Propiedad no asume responsabilidad alguna.\n"
                + "                </h4>\n"
                + "                <h3 style=\"padding-left: 10px\">\n"
                + "                    3.1. DESCUENTOS\n"
                + "                </h3>\n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    Los descuentos establecidos en la Ordenanza No. 047-2017 (24-05-2017) aprobada por el Cabildo, se aplicarán únicamente \n"
                + "                    a los pagos que se realicen mediante la opción pago en “VENTANILLA DEL REGISTRO” Es decir, los pagos realizados mediante TARJETA BANCARIA NO APLICAN DESCUENTOS, \n"
                + "                    por ser pagos directos y la imposibilidad de verificar la información.     \n"
                + "                </h4>\n"
                + "                <h3 style=\"padding-left: 10px\">\n"
                + "                    4. BALCÓN DE SERVICIOS\n"
                + "                </h3>\n"
                + "                <h4 style=\"padding-left: 30px\">\n"
                + "                    La información brindada por medio de este servicio corresponderá a las Transferencias de Dominio realizadas \n"
                + "                    por el titular de la Cédula de Identidad, por el numero de Ficha Registral, por el Numero y Año de Inscripción o por los \n"
                + "                    Nombres y Apellidos ingresados por el solicitante.\n"
                + "                </h4>    ";
        return new ResponseEntity<>(body, HttpStatus.OK);
    }

}
